---
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - prepareCmd: "./scripts/release.sh ${nextRelease.version}"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
        - package-lock.json
        - src/system.json
      message: |-
        chore(release): ${nextRelease.version} [skip ci]
        ${nextRelease.notes}
  - - "@semantic-release/github"
    - assets:
        - dist/system.json
        - dist/GURPS.zip
preset: angular